/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AgentHeader from './AgentHeader';

/**
 * The Agents model module.
 * @module model/Agents
 * @version 0.1.0
 */
export default class Agents {
  /**
   * Constructs a new <code>Agents</code>.
   * @alias module:model/Agents
   * @class
   * @param agents {Array.<module:model/AgentHeader>} 
   */
  constructor(agents) {
    this.agents = agents;
  }

  /**
   * Constructs a <code>Agents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Agents} obj Optional instance to populate.
   * @return {module:model/Agents} The populated <code>Agents</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Agents();
      if (data.hasOwnProperty('agents'))
        obj.agents = ApiClient.convertToType(data['agents'], [AgentHeader]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/AgentHeader>} agents
 */
Agents.prototype.agents = undefined;

