/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Agent model module.
 * @module model/Agent
 * @version 0.1.0
 */
export default class Agent {
  /**
   * Constructs a new <code>Agent</code>.
   * @alias module:model/Agent
   * @class
   * @param id {String} 
   * @param version {String} 
   * @param name {String} 
   */
  constructor(id, version, name) {
    this.id = id;
    this.version = version;
    this.name = name;
  }

  /**
   * Constructs a <code>Agent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Agent} obj Optional instance to populate.
   * @return {module:model/Agent} The populated <code>Agent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Agent();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('shard'))
        obj.shard = ApiClient.convertToType(data['shard'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Agent.prototype.id = undefined;

/**
 * @member {String} version
 */
Agent.prototype.version = undefined;

/**
 * @member {String} name
 */
Agent.prototype.name = undefined;

/**
 * @member {String} shard
 */
Agent.prototype.shard = undefined;

/**
 * @member {String} code
 */
Agent.prototype.code = undefined;

