/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Direction from './Direction';

/**
 * The Boost model module.
 * @module model/Boost
 * @version 0.1.0
 */
export default class Boost {
  /**
   * Constructs a new <code>Boost</code>.
   * @alias module:model/Boost
   * @class
   * @param id {String} 
   * @param username {String} 
   * @param direction {module:model/Direction} 
   * @param _date {Date} 
   * @param amount {Number} 
   * @param post {String} 
   */
  constructor(id, username, direction, _date, amount, post) {
    this.id = id;
    this.username = username;
    this.direction = direction;
    this._date = _date;
    this.amount = amount;
    this.post = post;
  }

  /**
   * Constructs a <code>Boost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Boost} obj Optional instance to populate.
   * @return {module:model/Boost} The populated <code>Boost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Boost();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('direction'))
        obj.direction = Direction.constructFromObject(data['direction']);
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('post'))
        obj.post = ApiClient.convertToType(data['post'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Boost.prototype.id = undefined;

/**
 * @member {String} username
 */
Boost.prototype.username = undefined;

/**
 * @member {module:model/Direction} direction
 */
Boost.prototype.direction = undefined;

/**
 * @member {Date} _date
 */
Boost.prototype._date = undefined;

/**
 * @member {Number} amount
 */
Boost.prototype.amount = undefined;

/**
 * @member {String} post
 */
Boost.prototype.post = undefined;

