/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateTestwalletResp model module.
 * @module model/CreateTestwalletResp
 * @version 0.1.0
 */
export default class CreateTestwalletResp {
  /**
   * Constructs a new <code>CreateTestwalletResp</code>.
   * @alias module:model/CreateTestwalletResp
   * @class
   * @param key {String} 
   */
  constructor(key) {
    this.key = key;
  }

  /**
   * Constructs a <code>CreateTestwalletResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTestwalletResp} obj Optional instance to populate.
   * @return {module:model/CreateTestwalletResp} The populated <code>CreateTestwalletResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateTestwalletResp();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} key
 */
CreateTestwalletResp.prototype.key = undefined;

