/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CreateAgentReq model module.
 * @module model/CreateAgentReq
 * @version 0.1.0
 */
export default class CreateAgentReq {
  /**
   * Constructs a new <code>CreateAgentReq</code>.
   * @alias module:model/CreateAgentReq
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>CreateAgentReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAgentReq} obj Optional instance to populate.
   * @return {module:model/CreateAgentReq} The populated <code>CreateAgentReq</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAgentReq();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('shard'))
        obj.shard = ApiClient.convertToType(data['shard'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CreateAgentReq.prototype.name = undefined;

/**
 * @member {String} shard
 */
CreateAgentReq.prototype.shard = undefined;

/**
 * @member {String} code
 */
CreateAgentReq.prototype.code = undefined;

