/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeployTestReq model module.
 * @module model/DeployTestReq
 * @version 0.1.0
 */
export default class DeployTestReq {
  /**
   * Constructs a new <code>DeployTestReq</code>.
   * @alias module:model/DeployTestReq
   * @class
   * @param test {String} 
   */
  constructor(test) {
    this.test = test;
  }

  /**
   * Constructs a <code>DeployTestReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeployTestReq} obj Optional instance to populate.
   * @return {module:model/DeployTestReq} The populated <code>DeployTestReq</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeployTestReq();
      if (data.hasOwnProperty('env'))
        obj.env = ApiClient.convertToType(data['env'], 'String');
      if (data.hasOwnProperty('test'))
        obj.test = ApiClient.convertToType(data['test'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} env
 */
DeployTestReq.prototype.env = undefined;

/**
 * @member {String} test
 */
DeployTestReq.prototype.test = undefined;

