/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SignedContract from './SignedContract';

/**
 * The DeploySignedTestReq model module.
 * @module model/DeploySignedTestReq
 * @version 0.1.0
 */
export default class DeploySignedTestReq {
  /**
   * Constructs a new <code>DeploySignedTestReq</code>.
   * @alias module:model/DeploySignedTestReq
   * @class
   * @param test {module:model/SignedContract} 
   */
  constructor(test) {
    this.test = test;
  }

  /**
   * Constructs a <code>DeploySignedTestReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploySignedTestReq} obj Optional instance to populate.
   * @return {module:model/DeploySignedTestReq} The populated <code>DeploySignedTestReq</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeploySignedTestReq();
      if (data.hasOwnProperty('env'))
        obj.env = SignedContract.constructFromObject(data['env']);
      if (data.hasOwnProperty('test'))
        obj.test = SignedContract.constructFromObject(data['test']);
    }
    return obj;
  }
}

/**
 * @member {module:model/SignedContract} env
 */
DeploySignedTestReq.prototype.env = undefined;

/**
 * @member {module:model/SignedContract} test
 */
DeploySignedTestReq.prototype.test = undefined;

