/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeploySignedTestResp model module.
 * @module model/DeploySignedTestResp
 * @version 0.1.0
 */
export default class DeploySignedTestResp {
  /**
   * Constructs a new <code>DeploySignedTestResp</code>.
   * @alias module:model/DeploySignedTestResp
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeploySignedTestResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploySignedTestResp} obj Optional instance to populate.
   * @return {module:model/DeploySignedTestResp} The populated <code>DeploySignedTestResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeploySignedTestResp();
    }
    return obj;
  }
}
