/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeployTestResp model module.
 * @module model/DeployTestResp
 * @version 0.1.0
 */
export default class DeployTestResp {
  /**
   * Constructs a new <code>DeployTestResp</code>.
   * @alias module:model/DeployTestResp
   * @class
   * @param testContract {Array.<Number>} 
   */
  constructor(testContract) {
    this.testContract = testContract;
  }

  /**
   * Constructs a <code>DeployTestResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeployTestResp} obj Optional instance to populate.
   * @return {module:model/DeployTestResp} The populated <code>DeployTestResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeployTestResp();
      if (data.hasOwnProperty('env_contract'))
        obj.envContract = ApiClient.convertToType(data['env_contract'], ['Number']);
      if (data.hasOwnProperty('test_contract'))
        obj.testContract = ApiClient.convertToType(data['test_contract'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} envContract
 */
DeployTestResp.prototype.envContract = undefined;

/**
 * @member {Array.<Number>} testContract
 */
DeployTestResp.prototype.testContract = undefined;

