/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DeployAgentResp model module.
 * @module model/DeployAgentResp
 * @version 0.1.0
 */
export default class DeployAgentResp {
  /**
   * Constructs a new <code>DeployAgentResp</code>.
   * @alias module:model/DeployAgentResp
   * @class
   * @param contract {Array.<Number>} 
   */
  constructor(contract) {
    this.contract = contract;
  }

  /**
   * Constructs a <code>DeployAgentResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeployAgentResp} obj Optional instance to populate.
   * @return {module:model/DeployAgentResp} The populated <code>DeployAgentResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeployAgentResp();
      if (data.hasOwnProperty('contract'))
        obj.contract = ApiClient.convertToType(data['contract'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} contract
 */
DeployAgentResp.prototype.contract = undefined;

