/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Exchange model module.
 * @module model/Exchange
 * @version 0.1.0
 */
export default class Exchange {
  /**
   * Constructs a new <code>Exchange</code>.
   * @alias module:model/Exchange
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Exchange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exchange} obj Optional instance to populate.
   * @return {module:model/Exchange} The populated <code>Exchange</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Exchange();
    }
    return obj;
  }
}
