/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The InternalError model module.
 * @module model/InternalError
 * @version 0.1.0
 */
export default class InternalError {
  /**
   * Constructs a new <code>InternalError</code>.
   * @alias module:model/InternalError
   * @class
   * @param description {String} 
   */
  constructor(description) {
    this.description = description;
  }

  /**
   * Constructs a <code>InternalError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InternalError} obj Optional instance to populate.
   * @return {module:model/InternalError} The populated <code>InternalError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InternalError();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
InternalError.prototype.description = undefined;

