/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import LogLevel from './LogLevel';

/**
 * The Log model module.
 * @module model/Log
 * @version 0.1.0
 */
export default class Log {
  /**
   * Constructs a new <code>Log</code>.
   * @alias module:model/Log
   * @class
   * @param level {module:model/LogLevel} 
   * @param message {String} 
   */
  constructor(level, message) {
    this.level = level;
    this.message = message;
  }

  /**
   * Constructs a <code>Log</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Log} obj Optional instance to populate.
   * @return {module:model/Log} The populated <code>Log</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Log();
      if (data.hasOwnProperty('level'))
        obj.level = LogLevel.constructFromObject(data['level']);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/LogLevel} level
 */
Log.prototype.level = undefined;

/**
 * @member {String} message
 */
Log.prototype.message = undefined;

