/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class LogLevel.
 * @enum {String}
 * @readonly
 */
const LogLevel = {
  /**
   * value: "debug"
   * @const
   */
  debug: "debug",

  /**
   * value: "info"
   * @const
   */
  info: "info",

  /**
   * value: "error"
   * @const
   */
  error: "error",

  /**
   * Returns a <code>LogLevel</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/LogLevel} The enum <code>LogLevel</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {LogLevel};