/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RequestStatus from './RequestStatus';

/**
 * The Request model module.
 * @module model/Request
 * @version 0.1.0
 */
export default class Request {
  /**
   * Constructs a new <code>Request</code>.
   * @alias module:model/Request
   * @class
   * @param id {String} 
   * @param _date {Date} 
   * @param amount {Number} 
   * @param status {module:model/RequestStatus} 
   */
  constructor(id, _date, amount, status) {
    this.id = id;
    this._date = _date;
    this.amount = amount;
    this.status = status;
  }

  /**
   * Constructs a <code>Request</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Request} obj Optional instance to populate.
   * @return {module:model/Request} The populated <code>Request</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Request();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = RequestStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Request.prototype.id = undefined;

/**
 * @member {Date} _date
 */
Request.prototype._date = undefined;

/**
 * @member {Number} amount
 */
Request.prototype.amount = undefined;

/**
 * @member {module:model/RequestStatus} status
 */
Request.prototype.status = undefined;

