/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * Enum class RequestStatus.
 * @enum {String}
 * @readonly
 */
const RequestStatus = {
  /**
   * value: "done"
   * @const
   */
  done: "done",

  /**
   * value: "ongoing"
   * @const
   */
  ongoing: "ongoing",

  /**
   * value: "cancelled"
   * @const
   */
  cancelled: "cancelled",

  /**
   * Returns a <code>RequestStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/RequestStatus} The enum <code>RequestStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export default {RequestStatus};