/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SaveAgentResp model module.
 * @module model/SaveAgentResp
 * @version 0.1.0
 */
export default class SaveAgentResp {
  /**
   * Constructs a new <code>SaveAgentResp</code>.
   * @alias module:model/SaveAgentResp
   * @class
   * @param version {String} 
   * @param contract {Array.<Number>} 
   */
  constructor(version, contract) {
    this.version = version;
    this.contract = contract;
  }

  /**
   * Constructs a <code>SaveAgentResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveAgentResp} obj Optional instance to populate.
   * @return {module:model/SaveAgentResp} The populated <code>SaveAgentResp</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SaveAgentResp();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('contract'))
        obj.contract = ApiClient.convertToType(data['contract'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {String} version
 */
SaveAgentResp.prototype.version = undefined;

/**
 * @member {Array.<Number>} contract
 */
SaveAgentResp.prototype.contract = undefined;

