/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SignedTestDeplotError model module.
 * @module model/SignedTestDeplotError
 * @version 0.1.0
 */
export default class SignedTestDeplotError {
  /**
   * Constructs a new <code>SignedTestDeplotError</code>.
   * @alias module:model/SignedTestDeplotError
   * @class
   * @param error {String} 
   */
  constructor(error) {
    this.error = error;
  }

  /**
   * Constructs a <code>SignedTestDeplotError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignedTestDeplotError} obj Optional instance to populate.
   * @return {module:model/SignedTestDeplotError} The populated <code>SignedTestDeplotError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SignedTestDeplotError();
      if (data.hasOwnProperty('error'))
        obj.error = ApiClient.convertToType(data['error'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} error
 */
SignedTestDeplotError.prototype.error = undefined;

// Implement DeploySignedTestResp interface:
// Implement DeploySignedTestResp interface:
