/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SignedContract model module.
 * @module model/SignedContract
 * @version 0.1.0
 */
export default class SignedContract {
  /**
   * Constructs a new <code>SignedContract</code>.
   * @alias module:model/SignedContract
   * @class
   * @param contract {Array.<Number>} 
   * @param sig {Array.<Number>} 
   * @param sigAlgorithm {String} 
   * @param deployer {Array.<Number>} 
   */
  constructor(contract, sig, sigAlgorithm, deployer) {
    this.contract = contract;
    this.sig = sig;
    this.sigAlgorithm = sigAlgorithm;
    this.deployer = deployer;
  }

  /**
   * Constructs a <code>SignedContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignedContract} obj Optional instance to populate.
   * @return {module:model/SignedContract} The populated <code>SignedContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SignedContract();
      if (data.hasOwnProperty('contract'))
        obj.contract = ApiClient.convertToType(data['contract'], ['Number']);
      if (data.hasOwnProperty('sig'))
        obj.sig = ApiClient.convertToType(data['sig'], ['Number']);
      if (data.hasOwnProperty('sig_algorithm'))
        obj.sigAlgorithm = ApiClient.convertToType(data['sig_algorithm'], 'String');
      if (data.hasOwnProperty('deployer'))
        obj.deployer = ApiClient.convertToType(data['deployer'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} contract
 */
SignedContract.prototype.contract = undefined;

/**
 * @member {Array.<Number>} sig
 */
SignedContract.prototype.sig = undefined;

/**
 * @member {String} sigAlgorithm
 */
SignedContract.prototype.sigAlgorithm = undefined;

/**
 * @member {Array.<Number>} deployer
 */
SignedContract.prototype.deployer = undefined;

