/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Log from './Log';

/**
 * The SignedTestDeplotLogs model module.
 * @module model/SignedTestDeplotLogs
 * @version 0.1.0
 */
export default class SignedTestDeplotLogs {
  /**
   * Constructs a new <code>SignedTestDeplotLogs</code>.
   * @alias module:model/SignedTestDeplotLogs
   * @class
   * @param logs {Array.<module:model/Log>} 
   */
  constructor(logs) {
    this.logs = logs;
  }

  /**
   * Constructs a <code>SignedTestDeplotLogs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignedTestDeplotLogs} obj Optional instance to populate.
   * @return {module:model/SignedTestDeplotLogs} The populated <code>SignedTestDeplotLogs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SignedTestDeplotLogs();
      if (data.hasOwnProperty('logs'))
        obj.logs = ApiClient.convertToType(data['logs'], [Log]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Log>} logs
 */
SignedTestDeplotLogs.prototype.logs = undefined;

// Implement DeploySignedTestResp interface:
