/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TransferReq model module.
 * @module model/TransferReq
 * @version 0.1.0
 */
export default class TransferReq {
  /**
   * Constructs a new <code>TransferReq</code>.
   * @alias module:model/TransferReq
   * @class
   * @param from {String} 
   * @param to {String} 
   * @param amount {Number} 
   */
  constructor(from, to, amount) {
    this.from = from;
    this.to = to;
    this.amount = amount;
  }

  /**
   * Constructs a <code>TransferReq</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransferReq} obj Optional instance to populate.
   * @return {module:model/TransferReq} The populated <code>TransferReq</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransferReq();
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'String');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} from
 */
TransferReq.prototype.from = undefined;

/**
 * @member {String} to
 */
TransferReq.prototype.to = undefined;

/**
 * @member {Number} amount
 */
TransferReq.prototype.amount = undefined;

/**
 * @member {String} description
 */
TransferReq.prototype.description = undefined;

