/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Direction from './Direction';

/**
 * The Transfer model module.
 * @module model/Transfer
 * @version 0.1.0
 */
export default class Transfer {
  /**
   * Constructs a new <code>Transfer</code>.
   * @alias module:model/Transfer
   * @class
   * @param id {String} 
   * @param direction {module:model/Direction} 
   * @param _date {Date} 
   * @param amount {Number} 
   * @param toAddress {String} 
   * @param cost {Number} 
   */
  constructor(id, direction, _date, amount, toAddress, cost) {
    this.id = id;
    this.direction = direction;
    this._date = _date;
    this.amount = amount;
    this.toAddress = toAddress;
    this.cost = cost;
  }

  /**
   * Constructs a <code>Transfer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transfer} obj Optional instance to populate.
   * @return {module:model/Transfer} The populated <code>Transfer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Transfer();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('direction'))
        obj.direction = Direction.constructFromObject(data['direction']);
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('to_address'))
        obj.toAddress = ApiClient.convertToType(data['to_address'], 'String');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Transfer.prototype.id = undefined;

/**
 * @member {module:model/Direction} direction
 */
Transfer.prototype.direction = undefined;

/**
 * @member {Date} _date
 */
Transfer.prototype._date = undefined;

/**
 * @member {Number} amount
 */
Transfer.prototype.amount = undefined;

/**
 * @member {String} toAddress
 */
Transfer.prototype.toAddress = undefined;

/**
 * @member {Number} cost
 */
Transfer.prototype.cost = undefined;

