/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Boost from './Boost';
import Exchange from './Exchange';
import Request from './Request';
import Transfer from './Transfer';

/**
 * The WalletStateAndHistory model module.
 * @module model/WalletStateAndHistory
 * @version 0.1.0
 */
export default class WalletStateAndHistory {
  /**
   * Constructs a new <code>WalletStateAndHistory</code>.
   * @alias module:model/WalletStateAndHistory
   * @class
   * @param balance {Number} 
   * @param requests {Array.<module:model/Request>} 
   * @param exchanges {Array.<module:model/Exchange>} 
   * @param boosts {Array.<module:model/Boost>} 
   * @param transfers {Array.<module:model/Transfer>} 
   */
  constructor(balance, requests, exchanges, boosts, transfers) {
    this.balance = balance;
    this.requests = requests;
    this.exchanges = exchanges;
    this.boosts = boosts;
    this.transfers = transfers;
  }

  /**
   * Constructs a <code>WalletStateAndHistory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WalletStateAndHistory} obj Optional instance to populate.
   * @return {module:model/WalletStateAndHistory} The populated <code>WalletStateAndHistory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WalletStateAndHistory();
      if (data.hasOwnProperty('balance'))
        obj.balance = ApiClient.convertToType(data['balance'], 'Number');
      if (data.hasOwnProperty('requests'))
        obj.requests = ApiClient.convertToType(data['requests'], [Request]);
      if (data.hasOwnProperty('exchanges'))
        obj.exchanges = ApiClient.convertToType(data['exchanges'], [Exchange]);
      if (data.hasOwnProperty('boosts'))
        obj.boosts = ApiClient.convertToType(data['boosts'], [Boost]);
      if (data.hasOwnProperty('transfers'))
        obj.transfers = ApiClient.convertToType(data['transfers'], [Transfer]);
    }
    return obj;
  }
}

/**
 * @member {Number} balance
 */
WalletStateAndHistory.prototype.balance = undefined;

/**
 * @member {Array.<module:model/Request>} requests
 */
WalletStateAndHistory.prototype.requests = undefined;

/**
 * @member {Array.<module:model/Exchange>} exchanges
 */
WalletStateAndHistory.prototype.exchanges = undefined;

/**
 * @member {Array.<module:model/Boost>} boosts
 */
WalletStateAndHistory.prototype.boosts = undefined;

/**
 * @member {Array.<module:model/Transfer>} transfers
 */
WalletStateAndHistory.prototype.transfers = undefined;

