/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Agent from './model/Agent';
import AgentHeader from './model/AgentHeader';
import Agents from './model/Agents';
import Boost from './model/Boost';
import CreateAgentReq from './model/CreateAgentReq';
import CreateAgentResp from './model/CreateAgentResp';
import CreateTestwalletResp from './model/CreateTestwalletResp';
import DeployAgentResp from './model/DeployAgentResp';
import DeploySignedTestReq from './model/DeploySignedTestReq';
import DeploySignedTestResp from './model/DeploySignedTestResp';
import DeployTestReq from './model/DeployTestReq';
import DeployTestResp from './model/DeployTestResp';
import Direction from './model/Direction';
import Exchange from './model/Exchange';
import InternalError from './model/InternalError';
import Log from './model/Log';
import LogLevel from './model/LogLevel';
import Request from './model/Request';
import RequestStatus from './model/RequestStatus';
import SaveAgentResp from './model/SaveAgentResp';
import SignedContract from './model/SignedContract';
import SignedTestDeplotError from './model/SignedTestDeplotError';
import SignedTestDeplotLogs from './model/SignedTestDeplotLogs';
import Transfer from './model/Transfer';
import TransferReq from './model/TransferReq';
import TransferResp from './model/TransferResp';
import WalletStateAndHistory from './model/WalletStateAndHistory';
import AIAgentsApi from './api/AIAgentsApi';
import WalletsApi from './api/WalletsApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EmbersApi = require('index'); // See note below*.
* var xxxSvc = new EmbersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EmbersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EmbersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EmbersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Agent model constructor.
     * @property {module:model/Agent}
     */
    Agent,

    /**
     * The AgentHeader model constructor.
     * @property {module:model/AgentHeader}
     */
    AgentHeader,

    /**
     * The Agents model constructor.
     * @property {module:model/Agents}
     */
    Agents,

    /**
     * The Boost model constructor.
     * @property {module:model/Boost}
     */
    Boost,

    /**
     * The CreateAgentReq model constructor.
     * @property {module:model/CreateAgentReq}
     */
    CreateAgentReq,

    /**
     * The CreateAgentResp model constructor.
     * @property {module:model/CreateAgentResp}
     */
    CreateAgentResp,

    /**
     * The CreateTestwalletResp model constructor.
     * @property {module:model/CreateTestwalletResp}
     */
    CreateTestwalletResp,

    /**
     * The DeployAgentResp model constructor.
     * @property {module:model/DeployAgentResp}
     */
    DeployAgentResp,

    /**
     * The DeploySignedTestReq model constructor.
     * @property {module:model/DeploySignedTestReq}
     */
    DeploySignedTestReq,

    /**
     * The DeploySignedTestResp model constructor.
     * @property {module:model/DeploySignedTestResp}
     */
    DeploySignedTestResp,

    /**
     * The DeployTestReq model constructor.
     * @property {module:model/DeployTestReq}
     */
    DeployTestReq,

    /**
     * The DeployTestResp model constructor.
     * @property {module:model/DeployTestResp}
     */
    DeployTestResp,

    /**
     * The Direction model constructor.
     * @property {module:model/Direction}
     */
    Direction,

    /**
     * The Exchange model constructor.
     * @property {module:model/Exchange}
     */
    Exchange,

    /**
     * The InternalError model constructor.
     * @property {module:model/InternalError}
     */
    InternalError,

    /**
     * The Log model constructor.
     * @property {module:model/Log}
     */
    Log,

    /**
     * The LogLevel model constructor.
     * @property {module:model/LogLevel}
     */
    LogLevel,

    /**
     * The Request model constructor.
     * @property {module:model/Request}
     */
    Request,

    /**
     * The RequestStatus model constructor.
     * @property {module:model/RequestStatus}
     */
    RequestStatus,

    /**
     * The SaveAgentResp model constructor.
     * @property {module:model/SaveAgentResp}
     */
    SaveAgentResp,

    /**
     * The SignedContract model constructor.
     * @property {module:model/SignedContract}
     */
    SignedContract,

    /**
     * The SignedTestDeplotError model constructor.
     * @property {module:model/SignedTestDeplotError}
     */
    SignedTestDeplotError,

    /**
     * The SignedTestDeplotLogs model constructor.
     * @property {module:model/SignedTestDeplotLogs}
     */
    SignedTestDeplotLogs,

    /**
     * The Transfer model constructor.
     * @property {module:model/Transfer}
     */
    Transfer,

    /**
     * The TransferReq model constructor.
     * @property {module:model/TransferReq}
     */
    TransferReq,

    /**
     * The TransferResp model constructor.
     * @property {module:model/TransferResp}
     */
    TransferResp,

    /**
     * The WalletStateAndHistory model constructor.
     * @property {module:model/WalletStateAndHistory}
     */
    WalletStateAndHistory,

    /**
    * The AIAgentsApi service constructor.
    * @property {module:api/AIAgentsApi}
    */
    AIAgentsApi,

    /**
    * The WalletsApi service constructor.
    * @property {module:api/WalletsApi}
    */
    WalletsApi
};
