/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentHeader } from './AgentHeader';
import {
    AgentHeaderFromJSON,
    AgentHeaderFromJSONTyped,
    AgentHeaderToJSON,
    AgentHeaderToJSONTyped,
} from './AgentHeader';

/**
 * 
 * @export
 * @interface Agents
 */
export interface Agents {
    /**
     * 
     * @type {Array<AgentHeader>}
     * @memberof Agents
     */
    agents: Array<AgentHeader>;
}

/**
 * Check if a given object implements the Agents interface.
 */
export function instanceOfAgents(value: object): value is Agents {
    if (!('agents' in value) || value['agents'] === undefined) return false;
    return true;
}

export function AgentsFromJSON(json: any): Agents {
    return AgentsFromJSONTyped(json, false);
}

export function AgentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agents {
    if (json == null) {
        return json;
    }
    return {
        
        'agents': ((json['agents'] as Array<any>).map(AgentHeaderFromJSON)),
    };
}

export function AgentsToJSON(json: any): Agents {
    return AgentsToJSONTyped(json, false);
}

export function AgentsToJSONTyped(value?: Agents | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agents': ((value['agents'] as Array<any>).map(AgentHeaderToJSON)),
    };
}

