/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Direction } from './Direction';
import {
    DirectionFromJSON,
    DirectionFromJSONTyped,
    DirectionToJSON,
    DirectionToJSONTyped,
} from './Direction';

/**
 * 
 * @export
 * @interface Boost
 */
export interface Boost {
    /**
     * 
     * @type {string}
     * @memberof Boost
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Boost
     */
    username: string;
    /**
     * 
     * @type {Direction}
     * @memberof Boost
     */
    direction: Direction;
    /**
     * 
     * @type {Date}
     * @memberof Boost
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof Boost
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof Boost
     */
    post: string;
}



/**
 * Check if a given object implements the Boost interface.
 */
export function instanceOfBoost(value: object): value is Boost {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    return true;
}

export function BoostFromJSON(json: any): Boost {
    return BoostFromJSONTyped(json, false);
}

export function BoostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Boost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'direction': DirectionFromJSON(json['direction']),
        'date': (new Date(json['date'])),
        'amount': json['amount'],
        'post': json['post'],
    };
}

export function BoostToJSON(json: any): Boost {
    return BoostToJSONTyped(json, false);
}

export function BoostToJSONTyped(value?: Boost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'direction': DirectionToJSON(value['direction']),
        'date': ((value['date']).toISOString()),
        'amount': value['amount'],
        'post': value['post'],
    };
}

