/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAgentReq
 */
export interface CreateAgentReq {
    /**
     * 
     * @type {string}
     * @memberof CreateAgentReq
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentReq
     */
    shard?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentReq
     */
    code?: string;
}

/**
 * Check if a given object implements the CreateAgentReq interface.
 */
export function instanceOfCreateAgentReq(value: object): value is CreateAgentReq {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAgentReqFromJSON(json: any): CreateAgentReq {
    return CreateAgentReqFromJSONTyped(json, false);
}

export function CreateAgentReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentReq {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'shard': json['shard'] == null ? undefined : json['shard'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function CreateAgentReqToJSON(json: any): CreateAgentReq {
    return CreateAgentReqToJSONTyped(json, false);
}

export function CreateAgentReqToJSONTyped(value?: CreateAgentReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'shard': value['shard'],
        'code': value['code'],
    };
}

