/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTestwalletResp
 */
export interface CreateTestwalletResp {
    /**
     * 
     * @type {string}
     * @memberof CreateTestwalletResp
     */
    key: string;
}

/**
 * Check if a given object implements the CreateTestwalletResp interface.
 */
export function instanceOfCreateTestwalletResp(value: object): value is CreateTestwalletResp {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function CreateTestwalletRespFromJSON(json: any): CreateTestwalletResp {
    return CreateTestwalletRespFromJSONTyped(json, false);
}

export function CreateTestwalletRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestwalletResp {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function CreateTestwalletRespToJSON(json: any): CreateTestwalletResp {
    return CreateTestwalletRespToJSONTyped(json, false);
}

export function CreateTestwalletRespToJSONTyped(value?: CreateTestwalletResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

