/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeployTestReq
 */
export interface DeployTestReq {
    /**
     * 
     * @type {string}
     * @memberof DeployTestReq
     */
    env?: string;
    /**
     * 
     * @type {string}
     * @memberof DeployTestReq
     */
    test: string;
}

/**
 * Check if a given object implements the DeployTestReq interface.
 */
export function instanceOfDeployTestReq(value: object): value is DeployTestReq {
    if (!('test' in value) || value['test'] === undefined) return false;
    return true;
}

export function DeployTestReqFromJSON(json: any): DeployTestReq {
    return DeployTestReqFromJSONTyped(json, false);
}

export function DeployTestReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployTestReq {
    if (json == null) {
        return json;
    }
    return {
        
        'env': json['env'] == null ? undefined : json['env'],
        'test': json['test'],
    };
}

export function DeployTestReqToJSON(json: any): DeployTestReq {
    return DeployTestReqToJSONTyped(json, false);
}

export function DeployTestReqToJSONTyped(value?: DeployTestReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'env': value['env'],
        'test': value['test'],
    };
}

