/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignedContract } from './SignedContract';
import {
    SignedContractFromJSON,
    SignedContractFromJSONTyped,
    SignedContractToJSON,
    SignedContractToJSONTyped,
} from './SignedContract';

/**
 * 
 * @export
 * @interface DeploySignedTestReq
 */
export interface DeploySignedTestReq {
    /**
     * 
     * @type {SignedContract}
     * @memberof DeploySignedTestReq
     */
    env?: SignedContract;
    /**
     * 
     * @type {SignedContract}
     * @memberof DeploySignedTestReq
     */
    test: SignedContract;
}

/**
 * Check if a given object implements the DeploySignedTestReq interface.
 */
export function instanceOfDeploySignedTestReq(value: object): value is DeploySignedTestReq {
    if (!('test' in value) || value['test'] === undefined) return false;
    return true;
}

export function DeploySignedTestReqFromJSON(json: any): DeploySignedTestReq {
    return DeploySignedTestReqFromJSONTyped(json, false);
}

export function DeploySignedTestReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploySignedTestReq {
    if (json == null) {
        return json;
    }
    return {
        
        'env': json['env'] == null ? undefined : SignedContractFromJSON(json['env']),
        'test': SignedContractFromJSON(json['test']),
    };
}

export function DeploySignedTestReqToJSON(json: any): DeploySignedTestReq {
    return DeploySignedTestReqToJSONTyped(json, false);
}

export function DeploySignedTestReqToJSONTyped(value?: DeploySignedTestReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'env': SignedContractToJSON(value['env']),
        'test': SignedContractToJSON(value['test']),
    };
}

