/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalError
 */
export interface InternalError {
    /**
     * 
     * @type {string}
     * @memberof InternalError
     */
    description: string;
}

/**
 * Check if a given object implements the InternalError interface.
 */
export function instanceOfInternalError(value: object): value is InternalError {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function InternalErrorFromJSON(json: any): InternalError {
    return InternalErrorFromJSONTyped(json, false);
}

export function InternalErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalError {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function InternalErrorToJSON(json: any): InternalError {
    return InternalErrorToJSONTyped(json, false);
}

export function InternalErrorToJSONTyped(value?: InternalError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

