/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveAgentResp
 */
export interface SaveAgentResp {
    /**
     * 
     * @type {string}
     * @memberof SaveAgentResp
     */
    version: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof SaveAgentResp
     */
    contract: Array<number>;
}

/**
 * Check if a given object implements the SaveAgentResp interface.
 */
export function instanceOfSaveAgentResp(value: object): value is SaveAgentResp {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    return true;
}

export function SaveAgentRespFromJSON(json: any): SaveAgentResp {
    return SaveAgentRespFromJSONTyped(json, false);
}

export function SaveAgentRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveAgentResp {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'],
        'contract': json['contract'],
    };
}

export function SaveAgentRespToJSON(json: any): SaveAgentResp {
    return SaveAgentRespToJSONTyped(json, false);
}

export function SaveAgentRespToJSONTyped(value?: SaveAgentResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'contract': value['contract'],
    };
}

