/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignedContract
 */
export interface SignedContract {
    /**
     * 
     * @type {Array<number>}
     * @memberof SignedContract
     */
    contract: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof SignedContract
     */
    sig: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof SignedContract
     */
    sigAlgorithm: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof SignedContract
     */
    deployer: Array<number>;
}

/**
 * Check if a given object implements the SignedContract interface.
 */
export function instanceOfSignedContract(value: object): value is SignedContract {
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('sig' in value) || value['sig'] === undefined) return false;
    if (!('sigAlgorithm' in value) || value['sigAlgorithm'] === undefined) return false;
    if (!('deployer' in value) || value['deployer'] === undefined) return false;
    return true;
}

export function SignedContractFromJSON(json: any): SignedContract {
    return SignedContractFromJSONTyped(json, false);
}

export function SignedContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedContract {
    if (json == null) {
        return json;
    }
    return {
        
        'contract': json['contract'],
        'sig': json['sig'],
        'sigAlgorithm': json['sig_algorithm'],
        'deployer': json['deployer'],
    };
}

export function SignedContractToJSON(json: any): SignedContract {
    return SignedContractToJSONTyped(json, false);
}

export function SignedContractToJSONTyped(value?: SignedContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract': value['contract'],
        'sig': value['sig'],
        'sig_algorithm': value['sigAlgorithm'],
        'deployer': value['deployer'],
    };
}

