/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Log } from './Log';
import {
    LogFromJSON,
    LogFromJSONTyped,
    LogToJSON,
    LogToJSONTyped,
} from './Log';

/**
 * 
 * @export
 * @interface SignedTestDeplotLogs
 */
export interface SignedTestDeplotLogs {
    /**
     * 
     * @type {Array<Log>}
     * @memberof SignedTestDeplotLogs
     */
    logs: Array<Log>;
}

/**
 * Check if a given object implements the SignedTestDeplotLogs interface.
 */
export function instanceOfSignedTestDeplotLogs(value: object): value is SignedTestDeplotLogs {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function SignedTestDeplotLogsFromJSON(json: any): SignedTestDeplotLogs {
    return SignedTestDeplotLogsFromJSONTyped(json, false);
}

export function SignedTestDeplotLogsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedTestDeplotLogs {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': ((json['logs'] as Array<any>).map(LogFromJSON)),
    };
}

export function SignedTestDeplotLogsToJSON(json: any): SignedTestDeplotLogs {
    return SignedTestDeplotLogsToJSONTyped(json, false);
}

export function SignedTestDeplotLogsToJSONTyped(value?: SignedTestDeplotLogs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': ((value['logs'] as Array<any>).map(LogToJSON)),
    };
}

