/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignedTestDeplotError
 */
export interface SignedTestDeplotError {
    /**
     * 
     * @type {string}
     * @memberof SignedTestDeplotError
     */
    error: string;
}

/**
 * Check if a given object implements the SignedTestDeplotError interface.
 */
export function instanceOfSignedTestDeplotError(value: object): value is SignedTestDeplotError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function SignedTestDeplotErrorFromJSON(json: any): SignedTestDeplotError {
    return SignedTestDeplotErrorFromJSONTyped(json, false);
}

export function SignedTestDeplotErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignedTestDeplotError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function SignedTestDeplotErrorToJSON(json: any): SignedTestDeplotError {
    return SignedTestDeplotErrorToJSONTyped(json, false);
}

export function SignedTestDeplotErrorToJSONTyped(value?: SignedTestDeplotError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

