/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferResp
 */
export interface TransferResp {
    /**
     * 
     * @type {Array<number>}
     * @memberof TransferResp
     */
    contract: Array<number>;
}

/**
 * Check if a given object implements the TransferResp interface.
 */
export function instanceOfTransferResp(value: object): value is TransferResp {
    if (!('contract' in value) || value['contract'] === undefined) return false;
    return true;
}

export function TransferRespFromJSON(json: any): TransferResp {
    return TransferRespFromJSONTyped(json, false);
}

export function TransferRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferResp {
    if (json == null) {
        return json;
    }
    return {
        
        'contract': json['contract'],
    };
}

export function TransferRespToJSON(json: any): TransferResp {
    return TransferRespToJSONTyped(json, false);
}

export function TransferRespToJSONTyped(value?: TransferResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract': value['contract'],
    };
}

