/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmbersApi);
  }
}(this, function(expect, EmbersApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EmbersApi.WalletsApi();
  });

  describe('(package)', function() {
    describe('WalletsApi', function() {
      describe('apiWalletsAddressStateGet', function() {
        it('should call apiWalletsAddressStateGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWalletsAddressStateGet call and complete the assertions
          /*

          instance.apiWalletsAddressStateGet(address, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EmbersApi.WalletStateAndHistory);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWalletsTransferPreparePost', function() {
        it('should call apiWalletsTransferPreparePost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWalletsTransferPreparePost call and complete the assertions
          /*

          instance.apiWalletsTransferPreparePost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EmbersApi.TransferResp);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWalletsTransferSendPost', function() {
        it('should call apiWalletsTransferSendPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWalletsTransferSendPost call
          /*

          instance.apiWalletsTransferSendPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
