// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq-generated-code.md

import type { WideOperationArgument } from "../../../../../../types.ts";
import type { OmitValueWhenNever } from "../../../../../../types.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../types.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../types.ts";
import type { SaveAgentResp } from "../../../../../components/schemas/SaveAgentResp.js";

export type HTTP_POST = (
  $: OmitValueWhenNever<{
    query: never;
    path: { id: string };
    headers: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: never;
        requiredHeaders: never;
        content: {
          "application/json; charset=utf-8": {
            schema: SaveAgentResp;
          };
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
  }>,
) =>
  | {
      status: 200;
      contentType?: "application/json; charset=utf-8";
      body?: SaveAgentResp;
    }
  | { status: 415; contentType: "text/plain"; body: string }
  | COUNTERFACT_RESPONSE
  | { ALL_REMAINING_HEADERS_ARE_OPTIONAL: COUNTERFACT_RESPONSE };
