/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAgentResp
 */
export interface CreateAgentResp {
    /**
     * 
     * @type {string}
     * @memberof CreateAgentResp
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAgentResp
     */
    version: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateAgentResp
     */
    contract: Array<number>;
}

/**
 * Check if a given object implements the CreateAgentResp interface.
 */
export function instanceOfCreateAgentResp(value: object): value is CreateAgentResp {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    return true;
}

export function CreateAgentRespFromJSON(json: any): CreateAgentResp {
    return CreateAgentRespFromJSONTyped(json, false);
}

export function CreateAgentRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAgentResp {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'version': json['version'],
        'contract': json['contract'],
    };
}

export function CreateAgentRespToJSON(json: any): CreateAgentResp {
    return CreateAgentRespToJSONTyped(json, false);
}

export function CreateAgentRespToJSONTyped(value?: CreateAgentResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'contract': value['contract'],
    };
}

