/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeployAgentResp
 */
export interface DeployAgentResp {
    /**
     * 
     * @type {Array<number>}
     * @memberof DeployAgentResp
     */
    contract: Array<number>;
}

/**
 * Check if a given object implements the DeployAgentResp interface.
 */
export function instanceOfDeployAgentResp(value: object): value is DeployAgentResp {
    if (!('contract' in value) || value['contract'] === undefined) return false;
    return true;
}

export function DeployAgentRespFromJSON(json: any): DeployAgentResp {
    return DeployAgentRespFromJSONTyped(json, false);
}

export function DeployAgentRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeployAgentResp {
    if (json == null) {
        return json;
    }
    return {
        
        'contract': json['contract'],
    };
}

export function DeployAgentRespToJSON(json: any): DeployAgentResp {
    return DeployAgentRespToJSONTyped(json, false);
}

export function DeployAgentRespToJSONTyped(value?: DeployAgentResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract': value['contract'],
    };
}

