/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LogLevel = {
    Debug: 'debug',
    Info: 'info',
    Error: 'error'
} as const;
export type LogLevel = typeof LogLevel[keyof typeof LogLevel];


export function instanceOfLogLevel(value: any): boolean {
    for (const key in LogLevel) {
        if (Object.prototype.hasOwnProperty.call(LogLevel, key)) {
            if (LogLevel[key as keyof typeof LogLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LogLevelFromJSON(json: any): LogLevel {
    return LogLevelFromJSONTyped(json, false);
}

export function LogLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogLevel {
    return json as LogLevel;
}

export function LogLevelToJSON(value?: LogLevel | null): any {
    return value as any;
}

export function LogLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): LogLevel {
    return value as LogLevel;
}

