/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferReq
 */
export interface TransferReq {
    /**
     * 
     * @type {string}
     * @memberof TransferReq
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof TransferReq
     */
    to: string;
    /**
     * 
     * @type {number}
     * @memberof TransferReq
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransferReq
     */
    description?: string;
}

/**
 * Check if a given object implements the TransferReq interface.
 */
export function instanceOfTransferReq(value: object): value is TransferReq {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TransferReqFromJSON(json: any): TransferReq {
    return TransferReqFromJSONTyped(json, false);
}

export function TransferReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferReq {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'amount': json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function TransferReqToJSON(json: any): TransferReq {
    return TransferReqToJSONTyped(json, false);
}

export function TransferReqToJSONTyped(value?: TransferReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
        'amount': value['amount'],
        'description': value['description'],
    };
}

