/* tslint:disable */
/* eslint-disable */
/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Direction } from './Direction';
import {
    DirectionFromJSON,
    DirectionFromJSONTyped,
    DirectionToJSON,
    DirectionToJSONTyped,
} from './Direction';

/**
 * 
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    id: string;
    /**
     * 
     * @type {Direction}
     * @memberof Transfer
     */
    direction: Direction;
    /**
     * 
     * @type {Date}
     * @memberof Transfer
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof Transfer
     */
    toAddress: string;
    /**
     * 
     * @type {number}
     * @memberof Transfer
     */
    cost: number;
}



/**
 * Check if a given object implements the Transfer interface.
 */
export function instanceOfTransfer(value: object): value is Transfer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    return true;
}

export function TransferFromJSON(json: any): Transfer {
    return TransferFromJSONTyped(json, false);
}

export function TransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transfer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'direction': DirectionFromJSON(json['direction']),
        'date': (new Date(json['date'])),
        'amount': json['amount'],
        'toAddress': json['to_address'],
        'cost': json['cost'],
    };
}

export function TransferToJSON(json: any): Transfer {
    return TransferToJSONTyped(json, false);
}

export function TransferToJSONTyped(value?: Transfer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'direction': DirectionToJSON(value['direction']),
        'date': ((value['date']).toISOString()),
        'amount': value['amount'],
        'to_address': value['toAddress'],
        'cost': value['cost'],
    };
}

