/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmbersApi);
  }
}(this, function(expect, EmbersApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeployTestResp', function() {
      beforeEach(function() {
        instance = new EmbersApi.DeployTestResp();
      });

      it('should create an instance of DeployTestResp', function() {
        // TODO: update the code to test DeployTestResp
        expect(instance).to.be.a(EmbersApi.DeployTestResp);
      });

      it('should have the property envContract (base name: "env_contract")', function() {
        // TODO: update the code to test the property envContract
        expect(instance).to.have.property('envContract');
        // expect(instance.envContract).to.be(expectedValueLiteral);
      });

      it('should have the property testContract (base name: "test_contract")', function() {
        // TODO: update the code to test the property testContract
        expect(instance).to.have.property('testContract');
        // expect(instance.testContract).to.be(expectedValueLiteral);
      });

    });
  });

}));
