/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmbersApi);
  }
}(this, function(expect, EmbersApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Direction', function() {
      beforeEach(function() {
        instance = EmbersApi.Direction;
      });

      it('should create an instance of Direction', function() {
        // TODO: update the code to test Direction
        expect(instance).to.be.a('object');
      });

      it('should have the property incoming', function() {
        expect(instance).to.have.property('incoming');
        expect(instance.incoming).to.be("incoming");
      });

      it('should have the property outgoing', function() {
        expect(instance).to.have.property('outgoing');
        expect(instance.outgoing).to.be("outgoing");
      });

    });
  });

}));
