/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmbersApi);
  }
}(this, function(expect, EmbersApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Log', function() {
      beforeEach(function() {
        instance = new EmbersApi.Log();
      });

      it('should create an instance of Log', function() {
        // TODO: update the code to test Log
        expect(instance).to.be.a(EmbersApi.Log);
      });

      it('should have the property level (base name: "level")', function() {
        // TODO: update the code to test the property level
        expect(instance).to.have.property('level');
        // expect(instance.level).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

    });
  });

}));
