/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmbersApi);
  }
}(this, function(expect, EmbersApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LogLevel', function() {
      beforeEach(function() {
        instance = EmbersApi.LogLevel;
      });

      it('should create an instance of LogLevel', function() {
        // TODO: update the code to test LogLevel
        expect(instance).to.be.a('object');
      });

      it('should have the property debug', function() {
        expect(instance).to.have.property('debug');
        expect(instance.debug).to.be("debug");
      });

      it('should have the property info', function() {
        expect(instance).to.have.property('info');
        expect(instance.info).to.be("info");
      });

      it('should have the property error', function() {
        expect(instance).to.have.property('error');
        expect(instance.error).to.be("error");
      });

    });
  });

}));
