/*
 * Embers API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EmbersApi);
  }
}(this, function(expect, EmbersApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WalletStateAndHistory', function() {
      beforeEach(function() {
        instance = new EmbersApi.WalletStateAndHistory();
      });

      it('should create an instance of WalletStateAndHistory', function() {
        // TODO: update the code to test WalletStateAndHistory
        expect(instance).to.be.a(EmbersApi.WalletStateAndHistory);
      });

      it('should have the property balance (base name: "balance")', function() {
        // TODO: update the code to test the property balance
        expect(instance).to.have.property('balance');
        // expect(instance.balance).to.be(expectedValueLiteral);
      });

      it('should have the property requests (base name: "requests")', function() {
        // TODO: update the code to test the property requests
        expect(instance).to.have.property('requests');
        // expect(instance.requests).to.be(expectedValueLiteral);
      });

      it('should have the property exchanges (base name: "exchanges")', function() {
        // TODO: update the code to test the property exchanges
        expect(instance).to.have.property('exchanges');
        // expect(instance.exchanges).to.be(expectedValueLiteral);
      });

      it('should have the property boosts (base name: "boosts")', function() {
        // TODO: update the code to test the property boosts
        expect(instance).to.have.property('boosts');
        // expect(instance.boosts).to.be(expectedValueLiteral);
      });

      it('should have the property transfers (base name: "transfers")', function() {
        // TODO: update the code to test the property transfers
        expect(instance).to.have.property('transfers');
        // expect(instance.transfers).to.be(expectedValueLiteral);
      });

    });
  });

}));
